name: CXARM CI

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

env:
  IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ touchgfx, webserver ]
        tag:
        - 9.70.2
        - 9.70.1
        - 9.60.4
    container:
      image: ghcr.io/iarsystems/arm:${{ matrix.tag }}-st
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run:  iarbuild ${{ matrix.project }}/EWARM/${{ matrix.project }}.ewp -make "*" -parallel `nproc`
    - name: Analyze
      continue-on-error: true
      run: |
        iarbuild ${{ matrix.project }}/EWARM/${{ matrix.project }}.ewp -cstat_analyze "*" `nproc`
