name: CXARM CI

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

env:
  IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

jobs:
  arm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ touchgfx, webserver ]
        tag:
        - 9.70.2
        - 9.70.1
        - 9.60.4
        command:
        - cstat_analyze
        - make
    container:
      image: ghcr.io/iarsystems/arm:${{ matrix.tag }}-st
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v5
    - run: |
        iarbuild ${{ matrix.project }}/EWARM/${{ matrix.project }}.ewp \
          -${{ matrix.command }} "*" \
          -log all \
          -parallel `nproc`
