name: CXARM CI

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

env:
  IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        echo "matrix={\"project\":[\"touchgfx\",\"webserver\"],\"tag\":[\"9.70.2\",\"9.70.1\",\"9.60.4\"]}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    container:
      image: ghcr.io/iarsystems/arm:${{ matrix.tag }}-st
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v5
    - run: |
        iarbuild ${{ matrix.project }}/EWARM/${{ matrix.project }}.ewp \
          -make "*" 
          -parallel `nproc`

  analyze:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    container:
      image: ghcr.io/iarsystems/arm:${{ matrix.tag }}-st
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v5
    - run: |
        iarbuild ${{ matrix.project }}/EWARM/${{ matrix.project }}.ewp \
          -cstat_cmds "*"
    - name: cstat
      id: cstat
      continue-on-error: true
      run: |
        icstat \
          --db cstat.db \
          --parallel `nproc` \
          commands $(find -iname "cstatcommands.txt")
        echo ::set-output ec=exit_status::$?
    - name: Error handling
      if: steps.cstat.outputs.exit_status != 0 | steps.cstat.outputs.exit_status != 4
      run: exit 1

          
